site_name: become.sh
docs_dir: './docs'

nav:
  - Prérequis:
    - Introduction : index.md
    - Matériel : matos.md
    - La virtualisation avec Proxmox : proxmox.md
    - Installer debian : debian.md
    - Un assistant efficace : hassio.md
  - Services:
    - IA locale avec Ollama: services/ollama.md
    - Streaming avec Jellyfin : services/jellyfin.md
  - Outils & scripts:
    - Scripts && commandes : outils/commandes.md
    - Logiciels recommandés : outils/softwares.md
    - Autres ressources : outils/links.md
    
use_directory_urls: true

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  features:
    - content.code.copy
    - search.suggest
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - navigation.top
  language: fr
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/server-network
  include_homepage_in_sidebar: false
  sticky_navigation: true
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Allumer la lumière
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Eteindre la lumière
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Suivre le système


plugins:
  - search
  - awesome-pages
  
repo_url: https://github.com/adenyrr/become.sh

extra:  
  consent:
    title: On a des cookies !
    description: >- 
      On utilise des cookies ici. Pas beaucoup, c'est juste pour compter les gens qui passent et savoir quels sujets sont les plus regardés.
  analytics: 
  feedback:
    title: Cette page vous a aidé ?
    ratings:
      - icon: material/emoticon-happy-outline
        name: Cette page est vraiment utile !
        data: 1
        note: >-
          Merci pour le feedback !
      - icon: material/emoticon-sad-outline
        name: Cette page pourrait être améliorée.
        data: 0
        note: >- 
          Merci pour le feedback !
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adenyrr/become.sh
    - icon: fontawesome/brands/discord
      link: https://discord.gg/AE8ZQ6Gcvz
          
copyright: CC - BY (adenyr)

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.arithmatex
  - pymdownx.b64
  - pymdownx.betterem
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.pathconverter
  - pymdownx.progressbar
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.striphtml
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - full_yaml_metadata
      
