site_name: become.sh
docs_dir: './docs'
nav:
  - Home: index.md
  - About: about.md
theme:
  name: ivory
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  features:
    - search.suggest
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - navigation.top
  language: fr
  font: false
  icon:
    logo: material/lightbulb
  include_homepage_in_sidebar: false
  sticky_navigation: true

plugins:
  - search
repo_url: https://github.com/adenyrr/become.sh
extra:  
  consent:
    title: On a des cookies !
    description: >- 
      On utilise des cookies ici. Pas beaucoup, c'est juste pour compter les gens qui passent et savoir quels sujets sont les plus regardés.
  analytics: 
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/emoticon-happy-outline
        name: This page was helpful
        data: 1
        note: >-
          Merci pour le feedback !
      - icon: material/emoticon-sad-outline
        name: This page could be improved
        data: 0
        note: >- 
          Merci pour le feedback !
copyright: CC - BY (adenyr)
