site_name: become.sh
docs_dir: './docs'

nav:
  - Pour débuter:
    - index.md
    - acheter.md
    - hassio.md
  - Hardware:
    - kesako.md
  - Services:
    - docker.md
  - Outils:
    - commandes.md
    - softwares.md
    - links.md
    
use_directory_urls: true

theme:
  name: ivory
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  features:
    - search.suggest
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - navigation.top
  language: fr
  font: false
  icon:
    logo: material/lightbulb
  include_homepage_in_sidebar: false
  sticky_navigation: true

plugins:
  - search
  - awesome-pages
  
repo_url: https://github.com/adenyrr/become.sh

extra:  
  consent:
    title: On a des cookies !
    description: >- 
      On utilise des cookies ici. Pas beaucoup, c'est juste pour compter les gens qui passent et savoir quels sujets sont les plus regardés.
  analytics: 
  feedback:
    title: Cette page vous a aidé ?
    ratings:
      - icon: material/emoticon-happy-outline
        name: Cette page est vraiment utile !
        data: 1
        note: >-
          Merci pour le feedback !
      - icon: material/emoticon-sad-outline
        name: Cette page pourrait être améliorée.
        data: 0
        note: >- 
          Merci pour le feedback !
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adenyrr/become.sh
    - icon: fontawesome/brands/discord
      link: https://discord.gg/AE8ZQ6Gcvz
          
copyright: CC - BY (adenyr)

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.b64
  - pymdownx.betterem
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.html
  - pymdownx.blocks.tab
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.pathconverter
  - pymdownx.progressbar
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.striphtml
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - full_yaml_metadata
